/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefSelectClientCertificateCallback_N */

#ifndef _Included_org_cef_callback_CefSelectClientCertificateCallback_N
#define _Included_org_cef_callback_CefSelectClientCertificateCallback_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefSelectClientCertificateCallback_N
 * Method:    N_Select
 * Signature: (JLorg/cef/security/CefX509Certificate;)V
 */
JNIEXPORT void JNICALL Java_org_cef_callback_CefSelectClientCertificateCallback_1N_N_1Select
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
