/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_security_CefX509Certificate_N */

#ifndef _Included_org_cef_security_CefX509Certificate_N
#define _Included_org_cef_security_CefX509Certificate_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_security_CefX509Certificate_N
 * Method:    N_Release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cef_security_CefX509Certificate_1N_N_1Release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
